#https://rust-coding-guidelines.github.io/rust-coding-guidelines-zh/safe-guides/Appendix/templates/rustfmt.toml.html

version = "Two"
# comments
wrap_comments = true
comment_width = 100
format_code_in_doc_comments = true

merge_derives = false
match_block_trailing_comma = true
format_macro_matchers = true
condense_wildcard_suffixes = true

group_imports = "StdExternalCrate"
imports_granularity = "Crate"




ignore = [
    "/build/",
    "/*-build/",
    "/build-*/",
    "/vendor/",
    # tests for now are not formatted, as they are sometimes pretty-printing constrained
    # (and generally rustfmt can move around comments in UI-testing incompatible ways)
    "src/tests",
    # do not format submodules
    "library/backtrace",
    "library/stdarch",
    "compiler/rustc_codegen_cranelift",
    "src/doc/book",
    "src/doc/edition-guide",
    "src/doc/embedded-book",
    "src/doc/nomicon",
    "src/doc/reference",
    "src/doc/rust-by-example",
    "src/doc/rustc-dev-guide",
    "src/llvm-project",
    "src/tools/cargo",
    "src/tools/clippy",
    "src/tools/miri",
    "src/tools/rls",
    "src/tools/rust-analyzer",
    "src/tools/rustfmt",
    "src/tools/rust-installer",
]